### PR TITLE
feat: add option to listen on specified address

### PR DESCRIPTION
**Pull request by ml-**

### CODE REVIEW

**Comment by nwtgck** [comment]
Thank you so much for the feature. I actually planed to add it in the future.

One thing I have not decided is the name of the option. I'd like to investigate exisiting applications for that name.

**Comment by nwtgck** [comment]
A candidate is `--host`. That is used in Go language, Node.js and nghttpx.

**Comment by ml-** [comment]
`--host` fits well to the existing options. Need a quick look into clap::Parser to see what's possible for the option description.
I'd like to make sure the user knows that not only IPv4 (127.0.0.0) but also IPv6 (::1) values are valid.

**Comment by nwtgck** [comment]
Thanks. I have the same idea. You can move `--host` to the top. I think the order of `host`, `port`,... is natural.

**Comment by nwtgck** [comment]
> Need a quick look into clap::Parser to see what's possible for the option description.

I conclude the parse implementation is `core::str::FromStr::from_str("127.0.0.1")` or `"127.0.0.1".parse::<std::net::IpAddr>()`.

Clap does not seem to have a direct parse implementation for std::net::IpAddr. Instead, clap tries to use `FromStr` trait. I experimented to parse my original `MyStruct` using clap. The following error message says `FromStr` is needed.

```
   Compiling piping-server v0.11.0 (/Users/ryo/dev/rust/piping-server-rust)
error[E0277]: the trait bound `MyStruct: FromStr` is not satisfied
   --> src/main.rs:36:5
    |
36  |     /// MyStruct option (parse test)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `FromStr` is not implemented for `MyStruct`
    |
note: required by `std::str::FromStr::from_str`
   --> /Users/ryo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/str/traits.rs:554:5
    |
554 |     fn from_str(s: &str) -> Result<Self, Self::Err>;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0277`.
error: could not compile `piping-server` due to previous error

```

**Comment by ml-** [comment]
Thanks for adjusting and merging! I am not well versed in rust yet and will try to be more considerate of other OSs, rust- or crate versions.

**Pull request merged**
